### ISSUE TITLE
Missing icons and other resources

### ISSUE THREAD

**Issue by bzuillsmith** [deckgo/deckdeckgo-website#15]
This is what my console looks like when I open the home page.

![image](https://user-images.githubusercontent.com/1412248/65547035-8b67ac00-decd-11e9-97de-f21a1846f926.png)

**Comment by peterpeterparker** [comment]
@bzuillsmith try a browser refresh it should solve the problem ("hard refresh", Shit+F5 like)

The fact that I modified the dns (beta.deckdeckgo.com -> deckdeckgo.com) and that you access it before maybe the reason

Let me know if it work out! Thx in advance

P.S.: Also we have a know little issue (https://github.com/deckgo/deckdeckgo/issues/355) we will solve soonish

**Comment by bzuillsmith** [comment]
That was it. Thanks!

**Comment by peterpeterparker** [comment]
whew, happy to hear that!

thx for the feedback
