### ISSUE TITLE
screen formatting - more Android LG K20 V

### ISSUE THREAD

**Issue by peterennis** [deckgo/deckdeckgo-website#6]
Here

![ddg2](https://user-images.githubusercontent.com/140737/59457295-03054580-8dcd-11e9-9206-471fc8532739.jpg)

**Comment by peterpeterparker** [comment]
should be good now or at least acceptable ;)

thx for the issue 👍

**Comment by peterennis** [comment]
Looks good.

![ddg5](https://user-images.githubusercontent.com/140737/59575310-c73dda80-906f-11e9-9dcf-d99854e47857.jpg)
