### ISSUE TITLE
padding needed above top headers

### ISSUE THREAD

**Issue by peterennis** [deckgo/deckdeckgo-website#8]
Here:

![ddg4](https://user-images.githubusercontent.com/140737/59575388-3287ac80-9070-11e9-9d76-c6081f074de4.jpg)

The header is close to the menu dropdown and looks crowded.
It is not noticeable on other pages as they have shorter text lines.

There is lots of space before the chart.

**Comment by peterpeterparker** [comment]
Thx. Should be a bit better now, I could live with it currently I've to say ;)
